### ISSUE TITLE
Text on buttons obscured in the GradientsGUI

### ISSUE THREAD

**Issue by rljacobson** [mfroeling/QMRITools#11]
**Describe the bug**
See attached screenshot. The labels on the buttons cannot be read. 

**To Reproduce**
1. Scroll to the section DTI and IVIM
2. Evaluate all cells in the Generating diffusion gradients section.

**Screenshots**
<img width="339" alt="screen shot 2019-02-24 at 3 32 25 pm" src="https://user-images.githubusercontent.com/1412598/53453884-7c7e5100-39f3-11e9-87a2-f09735f8abd8.png">

**Additional context**
I have a 27inch high dpi iMac display. 
<img width="200" alt="screen shot 2019-02-26 at 6 23 09 pm" src="https://user-images.githubusercontent.com/1412598/53453946-ab94c280-39f3-11e9-9437-65fe013b7fac.png">

**Comment by mfroeling** [comment]
I have fixed the font size of the button to 10pt (the size used on my windows system) and shortened the text in the buttons hopefully this will fix the issue. will commit asap
I cannot test this since i dont have a mac.

**Comment by mfroeling** [comment]
@rljacobson the 2.1 release should have the txt issue fixed. Could you please verify?

**Comment by mfroeling** [comment]
i have verified the txt is now readable, im closing the issue

![mac](https://user-images.githubusercontent.com/15890391/55061145-50e29b00-5073-11e9-917b-40f658b417d3.PNG)

**Comment by rljacobson** [comment]
Looks good!
