### ISSUE TITLE
Minor Issues and Suggestions

### ISSUE THREAD

**Issue by rljacobson** [mfroeling/QMRITools#12]
This is a list of minor issues and suggestions.

- [x] `CompilebleFunctions` The documentation says it "generates a list of all compilable functions." It generates a table (a list of lists wrapped in `TableForm`) of compilable functions, not a `List`.  The function `` Compile`CompilerFunctions `` generates a list of compilable functions.
- [x] `SegmentMask[mask, n]` It is not clear what `SegmentMask` is doing. The docs say, "divides a mask in n equal segments along the slice direction." What does "equal segments" mean? Equal in area? Equal in height? The plot is of a color quantized image, but the legend is continuous and in unknown units.
- [x] For the ME-SE  (TSE) T2 mapping slice profiles, in `SimulateSliceEPG`, the axes are not labeled. 

The first one is picking nits. The second one might be my ignorance of the field of application.

**Comment by mfroeling** [comment]
thanks for the valuable comments. 

* I have updated the help description of CompilebleFunctions to 
"generates a formatted table of all compilable functions generated by Compile`CompilerFunctions."

* I have updated the help description of SegmentMask to 
"divides a mask in n segments along the slice direction, n must be an integer. The mask is divided in n equal parts where each parts has the same number of slices."

* I have added labels to the SimulateSliceEPG plot
![epg](https://user-images.githubusercontent.com/15890391/53478807-f6581e00-3a77-11e9-9b84-7c5a5c53ca57.PNG)

**Comment by mfroeling** [comment]
@rljacobson can i close this issue?
