### ISSUE TITLE
Better default path for data in demo notebook

### ISSUE THREAD

**Issue by JoshKarpel** [mfroeling/QMRITools#5]
The demo notebook uses `SetDirectory["D:\\Werk\\Workspace\\QMRITools\\DemoData"];` - perhaps it could be `SetDirectory[FileNameJoin[{NotebookDirectory[], "DemoData"}]];`, which is a better default for people cloning the package via git, with a comment that says to change it if the demo data is somewhere else?

(Part of https://github.com/openjournals/joss-reviews/issues/1204)

**Comment by mfroeling** [comment]
Indeed that should be the correct path specification.

I have changed it in the `demo.nb` and have also added some explanation in the readme
