### ISSUE TITLE
Use GitHub's "releases" feature to distribute binaries/zip files

### ISSUE THREAD

**Issue by rljacobson** [mfroeling/QMRITools#9]
**Is your feature request related to a problem? Please describe.**

It is generally best practice to avoid committing binary files such as compiled executables and zip files, as they are usually impossible to diff, add significantly to the size of the repository, and are derivable from the contents of the repository anyway. Committing binaries used to be difficult to avoid if one wished to distribute binaries for a release on GitHub.

**Describe the solution you'd like**

GitHub has recently enabled attaching files to releases: https://help.github.com/articles/creating-releases/. Now, when you create a release for a version tag, you can attach a zip file or any other binary data to the release on GitHub. Here is what it looks like on one of my GitHub repositories: https://github.com/rljacobson/Levenshtein/releases.

**Additional context**

This is only a suggestion. Feel free to disregard it if you feel it's not the right thing for your project.

**Comment by mfroeling** [comment]
@rljacobson 
Thanks i did this for the latest release but i think it is indeed also the best practice for the demos data and files directory and the documentation build.

I was planning on making a new release shortly and will provide these files as zip in the release in stead of making them part in the git commit.

**Comment by mfroeling** [comment]
I have added all data files from the commit and moved them to zip files in the release page. 
i have updated links where needed in the readme and paper.

**Comment by mfroeling** [comment]
I have made a new prerelease with all files and binaries.
